version: '3'

services:
  python-script:
    image: $IMAGE
    entrypoint: 
      - python
      - ${SCRIPT}
    volumes:
      - ${HOSTPATH_PROJECT}:/home/student/projects
      - ${HOSTPATH_SCRIPTS}:/home/student/scripts