version: '3.7'

services:
  python-script:
    container_name: $CONTAINER_NAME
    image: $IMAGE
    pull_policy: always
    entrypoint: 
      - python
      - ${SCRIPT}
    volumes:
      - ${HOSTPATH_PROJECT}:/home/student/projects
      - ${HOSTPATH_SCRIPTS}:/home/student/scripts